# Site settings
title: Mopolo.fr
timezone: Europe/Paris
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mopolo.fr" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
collections:
  projects:
    output: false
  works:
    output: false
  games:
    output: true
    permalink: /games/:title:output_ext
